pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: clone
  jobs:
  - job: clone_repo
    container: 'bitnami/git:2.39.1'
    steps:
    - script: git clone https://github.com/yaichZied/example-repo.git

- stage: init 
  jobs:
  - job: init_terraform
    container: 
      image: 'swissgrc/azure-pipelines-terraform:latest'
    steps:
      - bash: |
          terraform init
      - task: CopyFiles@2
        displayName: 'Copy scripts'
        inputs:
          contents: |
            .terraform.lock.hcl
            .terraform/**
          targetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: terraform_init
  dependsOn: clone 

- stage: plan
  jobs:
  - job: plan_terraform
    container: 
      image: 'swissgrc/azure-pipelines-terraform:latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'terraform_init'
          targetPath: $(Build.SourcesDirectory)
      - bash: |
          chmod +x .terraform/providers/registry.terraform.io/hashicorp/azurerm/3.0.0/linux_amd64/terraform-provider-azurerm_v3.0.0_x5
          terraform plan
  dependsOn: 
      - clone
      - init


